# render.yaml
services:
  - type: web
    name: deepseek-free-api
    plan: free
    region: singapore
    env: node  # 指定 Node.js 环境
    buildCommand: |
      npm install
      npm run build  # 确保生成 dist 目录
    startCommand: "node dist/index.js"  # 启动路径需与构建输出一致
    envVars:
      - key: TZ
        value: Asia/Shanghai
