services:
  - type: web
    name: deepseek-free-api       # 服务名称（自定义）
    region: singapore             # 部署区域
    plan: free                    # 免费实例
    docker:
      image: vinlic/deepseek-free-api:latest
    envVars:
      - key: PORT
        value: 8000
        key: AUTHORIZATION
        value: "Bearer kxoHk99HzGSV+MMsY8YQ3Dbme71sMI6+/YrjZvr1ipR/9sKxFcDAUbQT1fBEsVHr"
      - key: TZ                   # 时区设置
        value: Asia/Shanghai
